apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ml-train
  namespace: argo
spec:
  entrypoint: train-model
  templates:
  - name: train-model
    container:
      image: saksh22/ml-train:latest
      command: ["python"]
      args: ["train.py"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
